# Generated by Django 6.0 on 2025-12-21 16:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='genre',
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['book_name'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='usersbooks',
            options={'ordering': ['-issue_date'], 'verbose_name': 'Выданная книга', 'verbose_name_plural': 'Выданные книги'},
        ),
        migrations.AddField(
            model_name='books',
            name='genre_type',
            field=models.CharField(choices=[('Fiction', 'Художественная литература'), ('Science', 'Наука'), ('History', 'История'), ('Fantasy', 'Фантастика'), ('Mystery', 'Детектив'), ('Other', 'Прочее')], default='Other', max_length=50, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='usersbooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_users', to='books.books', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='usersbooks',
            name='issue_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='usersbooks',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
        migrations.AlterField(
            model_name='usersbooks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
